/class:
  post:
    tags:
      - name: Class
    summary: Add new class
    parameters:
      - in: "body"
        name: "body"
        description: "Created member object"
        required: true
        schema:
          $ref: "#/components/schemas/Class"
    responses:
      200:
        schema:
          $ref: "#/components/schemas/Class"
  get:
    tags:
      - name: Class
    summary: List class
    responses:
      200:
        schema:
          type: "array"
          items:
            $ref: "#/components/schemas/Class"
/class/:id:
  get:
    tags:
      - name: Class
    summary: get class by id
    parameters:
      - in: params
        name: id
        type: string
        required: true
        description: Class id
    responses:
      200:
        schema:
          type: "array"
          items:
            $ref: "#/components/schemas/Class"
/class/:owner:
  get:
    tags:
      - name: Class
    summary: Get class by owner
    parameters:
      - in: params
        name: id
        type: string
        required: true
        description: owner id
    responses:
      200:
        schema:
          type: "array"
          items:
            $ref: "#/components/schemas/Class"
/class/discipline/:id:
  get:
    tags:
      - name: Class
    summary: Get class by discipline
    parameters:
      - in: params
        name: id
        type: string
        required: true
        description: discipline id
    responses:
      200:
        schema:
          type: "array"
          items:
            $ref: "#/components/schemas/Class"
